name 'macsmaxlb'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures macsmaxlb'
long_description 'Installs/Configures macsmaxlb'
version '0.1.0'
