name 'macsmaxapp'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures macsmaxapp'
long_description 'Installs/Configures macsmaxapp'
version '0.1.0'
